language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements-dev.txt
before_script:
  - make lint
# command to run tests
script:
  pytest
after_success:
  coveralls
